name = "recreation-management-api"
main = "src/index.ts"
compatibility_date = "2024-05-15"

# ローカル開発用の設定
[env.development]
vars = { NODE_ENV = "development" }

# 本番用D1データベース設定（後で設定）
[[d1_databases]]
binding = "DB"
database_name = "recreation-db"
database_id = "your-database-id-here"